# Generated by Django 6.0.6 on 2026-06-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_image_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='vendor',
            new_name='owner',
        ),
    ]
